### ISSUE TITLE
Vim and Hyper theme colour mismatch

### ISSUE THREAD

**Issue by grantbevis** [dracula/hyper#9] opened 2019-01-10 21:55 UTC
Hi there,

I'm trying to use the theme for my hyper shell and in vim but the colours aren't matching as per the following screenshot. I've removed any colour references for the background in my ~/.hyper.js but the background in vim doesn't match up. Is this a hyper or vim issue?
![screenshot 2019-01-10 at 21 50 26](https://user-images.githubusercontent.com/20246437/50999573-62abac00-1522-11e9-95fb-0e51677ca2ff.png)

**Comment by abdul-hamid-achik** [comment] 2019-05-07 17:48
has anyone found a solution for this?

**Comment by ThatLurker** [comment] 2019-09-16 22:40
Would setting vim's background as transparent fix this?

**Comment by vadimshvetsov** [comment] 2020-05-09 22:28
For me the issue is still exist.

I'm using this as workaround in my `.vimrc`:
```vim
highlight Normal ctermbg=None
```

**Comment by dangvanthanh** [comment] 2020-05-10 12:05
Hi @vadimshvetsov 

Can you share screenshot and vim's configuration?

**Comment by vadimshvetsov** [comment] 2020-05-10 22:06
Hi @dangvanthanh. Thanks for reacting my comment with reopening the issue.

Here is my [.vimrc](https://github.com/vadimshvetsov/dotfiles/blob/master/vim/.vimrc)

If I remove the line with setting `ctermbg=none` it looks like below:

![image](https://user-images.githubusercontent.com/16336572/81511696-dda5f200-9323-11ea-82de-275987f07cce.png)

**Comment by dangvanthanh** [comment] 2020-05-19 03:15
Thanks @vadimshvetsov 

I will investigate and fix soon.

**Comment by vadimshvetsov** [comment] 2020-05-20 01:51
Thanks, would be happy to test how it works

**Comment by grantbevis** [comment] 2020-07-23 06:31
Is this fixed? @dangvanthanh

**Comment by dangvanthanh** [comment] 2020-07-23 06:59
Hi @b3vis 

I was updated theme color by https://draculatheme.com/contribute#theme

**Comment by grantbevis** [comment] 2020-07-24 10:21
This still hasn't fixed the issue, I've updated my vim colour theme and ensured Hyper has the latest plugin version

![image](https://user-images.githubusercontent.com/20246437/88382143-c1044c80-cd9f-11ea-9c99-b0e0feac619f.png)

**Comment by dangvanthanh** [comment] 2020-07-27 09:04
@b3vis 

I will re-open and investigate your case.

**Comment by ooloth** [comment] 2020-07-30 03:15
In `.vimrc` this should be fixed by adding these lines before the line with `colorscheme dracula`:

```
let g:dracula_colorterm = 0
let g:dracula_italic = 0
```

See: https://github.com/dracula/vim/issues/96

**Comment by grantbevis** [comment] 2020-07-30 07:33
that fixed it for me, thanks @ooloth

**Comment by dangvanthanh** [comment] 2020-07-30 08:40
Thank @ooloth

**Comment by renan-eccel** [comment] 2021-03-09 14:07
I had the same problem. It seems that macOS Big Sur broke italics in vim.
@b3vis, if you want to make italics happen in your vim try to add these lines to `.vimrc`:

```
let &t_ZH="\e[3m"
let &t_ZR="\e[23m"
```

(remember to reset `g:dracula_italic = 1`)
source: https://stackoverflow.com/a/53625973/10012333

**Closed as completed** 2021-08-29 14:57 UTC
Labels: bug
